### ISSUE TITLE
Error in rule ciri_run_ciri_RNASE:

### ISSUE THREAD

**Issue by byee4** [algaebrown/circSTAMP_pipe#3]
I've been hitting this error, wondering if this is a bug with Ciri?

```
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 64
Rules claiming more threads will be scaled down.
Select jobs to execute...

[Sun Aug 18 14:41:01 2024]
rule ciri_run_ciri_RNASE:
  input: /tscc/projects/ps-yeolab3/bay001/annotations/mm10/mm10.fa.amb, /tscc/projects/ps-yeolab3/bay001/annotations/mm10/hisat2_vM25/mm10.1.ht2, output/fastqs/siRBM15_3-trimmed-pair1.fastq.gz, output/fastqs/siRBM15_3-trimmed-pair2.fastq.gz, /tscc/projects/ps-yeolab4/software/circstamp/a7c4316/examples/ciriconfig_full_mm10.yaml
  output: output/align/siRBM15_3.sorted.bam, output/align/siRBM15_3.sorted.bam.bai, output/siRBM15_3.gtf, output/siRBM15_3.bed, output/gene/siRBM15_3_cov.gtf, output/gene/siRBM15_3_genes.list, output/gene/siRBM15_3_out.gtf, output/circ/siRBM15_3.ciri, output/circ/siRBM15_3_index.fa, output/circ/siRBM15_3_denovo.sorted.bam, output/circ/siRBM15_3_denovo.sorted.bam.bai
  jobid: 0
  benchmark: benchmarks/ciriquant.siRBM15_3.txt
  wildcards: sample_label=siRBM15_3
  resources: mem_mb=16000, disk_mb=13644, tmpdir=, cpus=1, runtime=60, nodes=1, partition=condo


    CIRIquant       -1 output/fastqs/siRBM15_3-trimmed-pair1.fastq.gz       -2 output/fastqs/siRBM15_3-trimmed-pair2.fastq.gz       --config /tscc/projects/ps-yeolab4/software/circstamp/a7c4316/examples/ciriconfig_full_mm10.yaml       --library-type 0       -o output/       -p siRBM15_3       -t 16
     
Activating singularity image /tscc/projects/ps-yeolab4/software/circstamp/c89ea98/bin/.singularity/17615172ccba48cb6ed25b00d5d08e49.simg
[Sun 2024-08-18 14:41:02] [INFO ] Input reads: siRBM15_3-trimmed-pair1.fastq.gz,siRBM15_3-trimmed-pair2.fastq.gz
[Sun 2024-08-18 14:41:02] [INFO ] Library type: unstranded
[Sun 2024-08-18 14:41:02] [INFO ] Output directory: /tscc/lustre/ddn/scratch/bay001/tao_circrna_20240812/temporary_data/RBM15_OE_KD_rar11_N2A/output, Output prefix: siRBM15_3
[Sun 2024-08-18 14:41:02] [INFO ] Config: mm10_gencode_vM25 Loaded
[Sun 2024-08-18 14:41:02] [INFO ] 64 CPU cores availble, using 16
[Sun 2024-08-18 14:41:02] [INFO ] Align RNA-seq reads to reference genome ..
[Sun 2024-08-18 14:54:04] [INFO ] Estimate gene abundance ..
[Sun 2024-08-18 14:57:57] [INFO ] No circRNA information provided, run CIRI2 for junction site prediction ..
[Sun 2024-08-18 14:57:57] [INFO ] Running BWA-mem mapping candidate reads ..
[Sun 2024-08-18 15:39:12] [INFO ] Running CIRI2 for circRNA detection ..
Traceback (most recent call last):
 File "/usr/local/bin/CIRIquant", line 11, in <module>
  load_entry_point('CIRIquant==1.1.2', 'console_scripts', 'CIRIquant')()
 File "/usr/local/lib/python2.7/site-packages/CIRIquant-1.1.2-py2.7.egg/CIRIquant/main.py", line 180, in main
  circ_parser.convert(bed_file)
 File "/usr/local/lib/python2.7/site-packages/CIRIquant-1.1.2-py2.7.egg/CIRIquant/utils.py", line 239, in convert
  circ_data = getattr(self, '_' + self.tool.lower())()
 File "/usr/local/lib/python2.7/site-packages/CIRIquant-1.1.2-py2.7.egg/CIRIquant/utils.py", line 146, in _ciri2
  with open(self.circ, 'r') as f:
IOError: [Errno 2] No such file or directory: '/tscc/lustre/ddn/scratch/bay001/tao_circrna_20240812/temporary_data/RBM15_OE_KD_rar11_N2A/output/circ/siRBM15_3.ciri'
[Sun Aug 18 15:39:56 2024]
Error in rule ciri_run_ciri_RNASE:
  jobid: 0
  output: output/align/siRBM15_3.sorted.bam, output/align/siRBM15_3.sorted.bam.bai, output/siRBM15_3.gtf, output/siRBM15_3.bed, output/gene/siRBM15_3_cov.gtf, output/gene/siRBM15_3_genes.list, output/gene/siRBM15_3_out.gtf, output/circ/siRBM15_3.ciri, output/circ/siRBM15_3_index.fa, output/circ/siRBM15_3_denovo.sorted.bam, output/circ/siRBM15_3_denovo.sorted.bam.bai
  shell:
     
    CIRIquant       -1 output/fastqs/siRBM15_3-trimmed-pair1.fastq.gz       -2 output/fastqs/siRBM15_3-trimmed-pair2.fastq.gz       --config /tscc/projects/ps-yeolab4/software/circstamp/a7c4316/examples/ciriconfig_full_mm10.yaml       --library-type 0       -o output/       -p siRBM15_3       -t 16
     
    (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job ciri_run_ciri_RNASE since they might be corrupted:
output/align/siRBM15_3.sorted.bam, output/align/siRBM15_3.sorted.bam.bai, output/gene/siRBM15_3_cov.gtf, output/gene/siRBM15_3_genes.list, output/gene/siRBM15_3_out.gtf
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
```

**Comment by algaebrown** [comment]
I think it might be out of memory.

Charlene

**Comment by byee4** [comment]
x_x

**Comment by algaebrown** [comment]
or this https://github.com/bioinfo-biols/CIRIquant/issues/9
